"""add author and remove role column for users

Revision ID: 0fcc63379ce0
Revises: fc72f5a10990
Create Date: 2023-08-09 07:43:53.037314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fcc63379ce0'
down_revision = '1f9f43cd4d04'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'authors',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('abstract', sa.Text(), nullable=True),
        sa.Column('job_title', sa.String(length=225), nullable=True),
        sa.Column('linkedin_profile_link', sa.String(length=225), nullable=True),
        sa.Column('github_profile_link', sa.String(length=225), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=225), autoincrement=False, nullable=False))
    op.drop_table('authors')
    # ### end Alembic commands ###
