"""Add author and user one-to-one relationship

Revision ID: a6ac32a92bc3
Revises: 0fcc63379ce0
Create Date: 2023-08-09 11:04:59.086732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6ac32a92bc3'
down_revision = '0fcc63379ce0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('author_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'authors', ['author_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'author_id')
    # ### end Alembic commands ###
