"""Make role not nullable

Revision ID: fc72f5a10990
Revises: 1f9f43cd4d04
Create Date: 2023-07-27 15:09:23.791056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc72f5a10990'
down_revision = '1f9f43cd4d04'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role', existing_type=sa.VARCHAR(length=225), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role', existing_type=sa.VARCHAR(length=225), nullable=True)
    # ### end Alembic commands ###
